# Generated by Django 5.0.3 on 2026-03-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inovasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inovasi',
            options={'verbose_name': 'Inovasi', 'verbose_name_plural': 'Inovasi'},
        ),
    ]
